#include "mainwindow.h"
#include <QApplication>
#include "ModelExample.h"

int main(int argc, char *argv[])
{
    // SMOKE TESTING - IF IT CRASHES - SOMETHING IS WRONG
    model::testing::engage();

    // AUTO GENERATED BY QT
    QApplication a(argc, argv);
    MainWindow w;
    w.show();

    return a.exec();
}
